-- Complete Roastah Database Export Script
-- This script exports all data from your current database for migration

-- Export roasters data
\copy (SELECT 'INSERT INTO roasters (id, user_id, business_name, business_type, business_address, city, state, zip_code, description, roasting_experience, philosophy, is_active, total_reviews, average_rating, total_sales, total_revenue, response_time, completion_rate, leaderboard_score, created_at, updated_at) VALUES (' || id || ', ' || quote_literal(user_id) || ', ' || quote_literal(business_name) || ', ' || quote_literal(business_type) || ', ' || COALESCE(quote_literal(business_address), 'NULL') || ', ' || COALESCE(quote_literal(city), 'NULL') || ', ' || COALESCE(quote_literal(state), 'NULL') || ', ' || COALESCE(quote_literal(zip_code), 'NULL') || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || COALESCE(quote_literal(roasting_experience), 'NULL') || ', ' || COALESCE(quote_literal(philosophy), 'NULL') || ', ' || is_active || ', ' || total_reviews || ', ' || average_rating || ', ' || total_sales || ', ' || total_revenue || ', ' || response_time || ', ' || completion_rate || ', ' || leaderboard_score || ', ' || quote_literal(created_at::text) || ', ' || quote_literal(updated_at::text) || ');' FROM roasters) TO 'migration_backup/02_roasters_data.sql' WITH (FORMAT csv, QUOTE '"', DELIMITER E'\t');

-- Export products data  
\copy (SELECT 'INSERT INTO products (id, roaster_id, name, description, price, stock_quantity, origin, roast_level, process, altitude, varietal, tasting_notes, images, state, is_unlisted, is_preorder, is_private, is_out_of_stock, is_scheduled, published_at, scheduled_publish_at, preorder_shipping_date, archived_at, rejected_at, rejection_reason, reviewed_by, reviewed_at, review_notes, is_active, created_at, updated_at) VALUES (' || id || ', ' || roaster_id || ', ' || quote_literal(name) || ', ' || COALESCE(quote_literal(description), 'NULL') || ', ' || price || ', ' || stock_quantity || ', ' || COALESCE(quote_literal(origin), 'NULL') || ', ' || quote_literal(roast_level) || ', ' || COALESCE(quote_literal(process), 'NULL') || ', ' || COALESCE(quote_literal(altitude), 'NULL') || ', ' || COALESCE(quote_literal(varietal), 'NULL') || ', ' || COALESCE(quote_literal(tasting_notes), 'NULL') || ', ' || CASE WHEN images IS NULL THEN 'NULL' ELSE quote_literal(images::text) END || ', ' || quote_literal(state) || ', ' || is_unlisted || ', ' || is_preorder || ', ' || is_private || ', ' || is_out_of_stock || ', ' || is_scheduled || ', ' || COALESCE(quote_literal(published_at::text), 'NULL') || ', ' || COALESCE(quote_literal(scheduled_publish_at::text), 'NULL') || ', ' || COALESCE(quote_literal(preorder_shipping_date::text), 'NULL') || ', ' || COALESCE(quote_literal(archived_at::text), 'NULL') || ', ' || COALESCE(quote_literal(rejected_at::text), 'NULL') || ', ' || COALESCE(quote_literal(rejection_reason), 'NULL') || ', ' || COALESCE(quote_literal(reviewed_by), 'NULL') || ', ' || COALESCE(quote_literal(reviewed_at::text), 'NULL') || ', ' || COALESCE(quote_literal(review_notes), 'NULL') || ', ' || is_active || ', ' || quote_literal(created_at::text) || ', ' || quote_literal(updated_at::text) || ');' FROM products) TO 'migration_backup/03_products_data.sql' WITH (FORMAT csv, QUOTE '"', DELIMITER E'\t');

-- Export orders data
\copy (SELECT 'INSERT INTO orders (id, user_id, stripe_payment_intent_id, status, total_amount, shipping_address, billing_address, notes, created_at, updated_at) VALUES (' || id || ', ' || quote_literal(user_id) || ', ' || COALESCE(quote_literal(stripe_payment_intent_id), 'NULL') || ', ' || quote_literal(status) || ', ' || total_amount || ', ' || quote_literal(shipping_address::text) || ', ' || COALESCE(quote_literal(billing_address::text), 'NULL') || ', ' || COALESCE(quote_literal(notes), 'NULL') || ', ' || quote_literal(created_at::text) || ', ' || quote_literal(updated_at::text) || ');' FROM orders) TO 'migration_backup/04_orders_data.sql' WITH (FORMAT csv, QUOTE '"', DELIMITER E'\t');

-- Export order_items data
\copy (SELECT 'INSERT INTO order_items (id, order_id, product_id, roaster_id, quantity, price, grind_size, status, created_at) VALUES (' || id || ', ' || order_id || ', ' || product_id || ', ' || roaster_id || ', ' || quantity || ', ' || price || ', ' || COALESCE(quote_literal(grind_size), 'NULL') || ', ' || quote_literal(status) || ', ' || quote_literal(created_at::text) || ');' FROM order_items) TO 'migration_backup/05_order_items_data.sql' WITH (FORMAT csv, QUOTE '"', DELIMITER E'\t');

-- Export cart_items data
\copy (SELECT 'INSERT INTO cart_items (id, user_id, product_id, quantity, grind_size, created_at) VALUES (' || id || ', ' || quote_literal(user_id) || ', ' || product_id || ', ' || quantity || ', ' || COALESCE(quote_literal(grind_size), 'NULL') || ', ' || quote_literal(created_at::text) || ');' FROM cart_items) TO 'migration_backup/06_cart_items_data.sql' WITH (FORMAT csv, QUOTE '"', DELIMITER E'\t');